# Generated by Django 4.2.5 on 2023-10-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nam", models.CharField(max_length=250)),
                ("img", models.ImageField(upload_to="pic")),
                ("des", models.TextField()),
            ],
        ),
    ]
