# Generated by Django 4.2.5 on 2023-10-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="people",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("na", models.CharField(max_length=250)),
                ("im", models.ImageField(upload_to="pics")),
                ("ab", models.TextField()),
            ],
        ),
    ]
